Repository submariner-io/subctl, pull requests merged in 2022-05, with the labels that each got.

#7 Remove e2e-all-k8s CI job
  .github/workflows/e2e-all-k8s.yml
Labels: ready-to-test

#8 Use client Producer from submariner-operator
  cmd/subctl/deploybroker.go
  cmd/subctl/diagnose.go
  cmd/subctl/execute/execute.go
  cmd/subctl/export.go
  cmd/subctl/join.go
  cmd/subctl/root.go
  cmd/subctl/uninstall.go
  go.sum
  internal/gather/gather.go
  internal/gather/types.go
  pkg/client/default_producer.go
  pkg/client/producer.go
  pkg/client/restconfig_producer.go
  pkg/cluster/info.go
  pkg/deploy/broker.go
  pkg/deploy/operator.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/service/export.go
  pkg/subctl/cmd/deploybroker.go
  pkg/subctl/cmd/diagnose/cni.go
  pkg/subctl/cmd/join.go
  pkg/subctl/cmd/uninstall.go
  pkg/subctl/operator/submarinerop/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test

#12 Remove Promethius test GHA
  .github/workflows/prometheus.yml
Labels: ready-to-test

#11 Reduce the E2E Full test matrix
  .github/workflows/e2e-full.yml
Labels: ready-to-test

#19 Use == instead of Strings.Compare()
  cmd/subctl/benchmark.go
  cmd/subctl/verify.go
  pkg/subctl/cmd/benchmark.go
Labels: ready-to-test

#22 Adjust the subctl path in the dist tarballs
  Makefile
Labels: ready-to-test

#20 Use pkg/names from submariner-operator
  internal/gather/gather.go
  internal/image/image.go
  internal/show/versions.go
  pkg/broker/ensure.go
  pkg/broker/rbac.go
  pkg/images/images.go
  pkg/subctl/operator/servicediscoverycr/ensure.go
  pkg/subctl/operator/submarinerop/deployment/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test

#21 Require Go 1.17
  go.mod
Labels: ready-to-test

#24 Use pkg/crd from submariner-operator
  pkg/broker/ensure.go
  pkg/crd/crd_suite_test.go
  pkg/crd/updater.go
  pkg/crd/updater_test.go
  pkg/deploy/broker.go
  pkg/gateway/crds.go
  pkg/lighthouse/crds.go
  pkg/subctl/operator/submarinerop/crds/ensure.go
  pkg/subctl/operator/submarinerop/ensure.go
Labels: ready-to-test

#23 Remove pkg/names
  pkg/names/names.go
Labels: ready-to-test

#25 Use pkg/images from submariner-operator
  internal/image/image.go
  internal/show/versions.go
  pkg/images/image_parsing_test.go
  pkg/images/images.go
Labels: ready-to-test

#26 Use pkg/lighthouse from submariner-operator
  pkg/broker/ensure.go
  pkg/lighthouse/crds.go
Labels: ready-to-test

#59 Extract a common ReadMetadataFile function
  pkg/cloud/aws/aws.go
  pkg/cloud/file.go
  pkg/cloud/gcp/gcp.go
  pkg/cloud/rhos/rhos.go
Labels: ready-to-test

#58 Remove flake finder periodic tests
  .github/workflows/flake_finder.yml
  README.md
Labels: ready-to-test, maintenance

#61 Restore image release on push GHA
  .github/workflows/release.yml
Labels: ready-to-test

#60 Update README to be about subctl repo
  README.md
Labels: documentation, ready-to-test, blocked-on-rereview

#72 Bump Submariner dependencies to 0.13.0-m2
  go.mod
  go.sum
Labels: ready-to-test
