Repository submariner-io/subctl, pull requests merged in 2022-11, with the labels that each got.

#346 Automated backport of #344: Avoid errors caused by sponge's SIGPIPE
  scripts/test/system.sh
Labels: ready-to-test, automated-backport

#333 Use --namespace for the broker namespace
  cmd/subctl/deploybroker.go
  internal/restconfig/restconfig.go
Labels: ready-to-test, backport

#356 Automated backport of #333: Use --namespace for the broker namespace
  cmd/subctl/deploybroker.go
  internal/restconfig/restconfig.go
Labels: ready-to-test, automated-backport

#349 subctl diagnose shows pod security warnings on OCP 4.12
  internal/pods/schedule.go
  pkg/operator/ensure.go
Labels: ready-to-test, backport

#357 Automated backport of #349: subctl diagnose shows pod security warnings on OCP 4.12
  internal/pods/schedule.go
  pkg/operator/ensure.go
Labels: ready-to-test, automated-backport

#355 Add release note for: #258
  release-notes/20221103-privileged-scc.md
Labels: ready-to-test

#353 Release note for #219
  release-notes/20220818-show-versions.md
Labels: ready-to-test

#364 Specify the namespace on deprecated verify
  cmd/subctl/verify.go
Labels: ready-to-test, backport

#365 Refactor `cloud prepare rhos` flag docs
  cmd/subctl/rhos.go
Labels: documentation, ready-to-test

#367 Automated backport of #364: Specify the namespace on deprecated verify
  cmd/subctl/verify.go
Labels: ready-to-test, automated-backport

#366 Fix operator OCP cluster role setup
  pkg/operator/ensure.go
Labels: ready-to-test, backport

#368 Automated backport of #366: Fix operator OCP cluster role setup
  pkg/operator/ensure.go
Labels: ready-to-test, automated-backport

#372 Use clusterID instead of clusterName to get endpoint
  pkg/diagnose/firewall.go
Labels: ready-to-test

#373 Automated backport of #372: Use clusterID instead of clusterName to get endpoint
  pkg/diagnose/firewall.go
Labels: ready-to-test, automated-backport

#374 Gather: capture CIDRs as part of summary.html page
  internal/gather/layout.gohtml
  internal/gather/summary.go
  internal/gather/types.go
Labels: ready-to-test

#375 Replace io/ioutil with os or io package
  internal/env/term_test.go
Labels: ready-to-test

#376 Bump sigs.k8s.io/controller-runtime from 0.12.3 to 0.13.1
  go.mod
  go.sum
Labels: ready-to-test

#381 Configure dependabot for 0.14
  .github/dependabot.yml
Labels: ready-to-test

#394 Look up service EndpointSlice by labels
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test

#393 Automated backport of #349: subctl diagnose shows pod security warnings on OCP 4.12
  internal/pods/schedule.go
  pkg/operator/ensure.go
  scripts/kind-e2e/lib_operator_verify_subm.sh
Labels: ready-to-test, automated-backport

#403 Pull in the leases fix from the operator
  go.mod
  go.sum
Labels: ready-to-test

#401 Sync subctl with other Submariner projects
  cmd/subctl/join.go
  go.mod
  go.sum
  internal/rbac/rbac.go
  internal/show/network.go
  pkg/broker/ensure.go
  pkg/broker/file.go
  pkg/broker/info.go
  pkg/brokercr/ensure.go
  pkg/cloud/prepare/prepare.go
  pkg/clusterrole/ensure.go
  pkg/clusterrole/ensure_test.go
  pkg/clusterrolebinding/ensure.go
  pkg/clusterrolebinding/ensure_test.go
  pkg/deploy/broker.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/deployment/await.go
  pkg/deployment/ensure.go
  pkg/deployment/ensure_test.go
  pkg/gateway/crds.go
  pkg/join/join.go
  pkg/lighthouse/ensure.go
  pkg/lighthouse/serviceaccount/ensure.go
  pkg/namespace/ensure.go
  pkg/operator/crds/ensure.go
  pkg/operator/deployment/ensure.go
  pkg/operator/ensure.go
  pkg/operator/ocp/ensure.go
  pkg/operator/serviceaccount/ensure.go
  pkg/role/ensure.go
  pkg/role/ensure_test.go
  pkg/rolebinding/ensure.go
  pkg/rolebinding/ensure_test.go
  pkg/secret/ensure.go
  pkg/serviceaccount/ensure.go
  pkg/serviceaccount/ensure_test.go
  pkg/servicediscoverycr/ensure.go
  pkg/submariner/ensure.go
  pkg/submariner/serviceaccount/ensure.go
  pkg/submarinercr/ensure.go
Labels: ready-to-test

#262 Add support for LB option in prepare command
  cmd/subctl/aws.go
  cmd/subctl/azure.go
  cmd/subctl/cloud.go
  cmd/subctl/gcp.go
  cmd/subctl/join.go
  cmd/subctl/rhos.go
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, release-note-needed
