Repository submariner-io/subctl, pull requests merged in 2022-08, with the labels that each got.

#192 Convert uses of operator clientset to controller Client
  cmd/subctl/deploybroker.go
  cmd/subctl/diagnose.go
  cmd/subctl/join.go
  cmd/subctl/uninstall.go
  go.mod
  go.sum
  internal/gather/gather.go
  internal/gather/types.go
  internal/show/brokers.go
  internal/show/versions.go
  pkg/brokercr/ensure.go
  pkg/cluster/info.go
  pkg/deploy/broker.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/servicediscoverycr/ensure.go
  pkg/submarinercr/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test

#188 Use ENV vars instead of flags
  Makefile
  scripts/test/lib_subctl_gather_test.sh
  scripts/test/system.sh
Labels: ready-to-test

#136 Gather creates a subdirectory with cluster name for gather logs
  cmd/subctl/gather.go
  internal/gather/gather.go
  internal/gather/logs.go
  internal/gather/resource.go
  scripts/test/lib_subctl_gather_test.sh
  scripts/test/system.sh
Labels: ready-to-test, release-note-needed

#197 Use controller client in CheckVersionMismatch
  internal/restconfig/restconfig.go
Labels: ready-to-test

#201 Use new client.Producer in gather
  internal/gather/gather.go
  internal/gather/types.go
Labels: ready-to-test

#200 Remove use of Shipyard `compile.sh` flags
  Makefile
Labels: ready-to-test

#202 Bump submariner-operator version and adjust to changes
  cmd/subctl/join.go
  go.mod
  go.sum
  internal/gather/gather.go
  internal/gather/operator.go
  internal/gather/types.go
  internal/image/image.go
  internal/restconfig/restconfig.go
  internal/show/brokers.go
  internal/show/network.go
  internal/show/versions.go
  pkg/brokercr/ensure.go
  pkg/cloud/prepare/prepare.go
  pkg/cluster/info.go
  pkg/deploy/broker.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/diagnose/firewall.go
  pkg/join/join.go
  pkg/servicediscoverycr/ensure.go
  pkg/submarinercr/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test

#203 Use new client.Producer for join and deploy broker
  cmd/subctl/deploybroker.go
  cmd/subctl/join.go
  cmd/subctl/root.go
  pkg/deploy/broker.go
  pkg/deploy/operator.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/operator/ensure.go
Labels: ready-to-test

#204 Use new client.Producer for diagnose
  cmd/subctl/diagnose.go
  cmd/subctl/root.go
  pkg/diagnose/cni.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_metrics.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/globalnet.go
  pkg/diagnose/kubeproxy.go
Labels: ready-to-test

#205 Use new client.Producer for uninstall
  cmd/subctl/uninstall.go
  pkg/uninstall/all.go
Labels: ready-to-test

#207 Remove remaining uses of submariner-operator client.Producer
  cmd/subctl/export.go
  internal/show/versions.go
  pkg/cluster/info.go
  pkg/service/export.go
Labels: ready-to-test

#208 Remove use of deprecated MCS SchemeGroupVersion
  pkg/diagnose/globalnet.go
  pkg/service/export.go
Labels: ready-to-test

#217 Add Anchore Go dependency security scanning
  .github/workflows/linting.yml
  .github/workflows/report.yml
  .grype.yaml
Labels: ready-to-test

#219 Fix `subctl show version` to show actual versions
  internal/show/versions.go
Labels: ready-to-test

#221 Only preload images used to deploy submariner
  Makefile
Labels: ready-to-test

#216 Remove deprecated --metrics-port
  cmd/subctl/cloud.go
Labels: ready-to-test

#223 Fix default image repo/version in compilation
  Makefile
Labels: ready-to-test

#215 Remove deprecated --ikeport
  cmd/subctl/join.go
Labels: ready-to-test, maintenance

#224 Wrapped error is always nil
  pkg/submariner/scc/ensure.go
Labels: ready-to-test

#212 Modify diagnose to query metrics
  cmd/subctl/diagnose.go
  pkg/cluster/info.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_metrics.go
Labels: ready-to-test

#232 Automated backport of #171: Mention default cable driver in join help msg
  cmd/subctl/join.go
Labels: ready-to-test, automated-backport

#228 cloud-prepare: Don't open metrics port
  cmd/subctl/cloud.go
  pkg/cloud/cloud.go
  pkg/cloud/prepare/prepare.go
Labels: ready-to-test, release-note-needed

#236 Minimize GHA permissions
  .github/workflows/branch.yml
  .github/workflows/codeowners.yml
  .github/workflows/cross.yml
  .github/workflows/dependent-issues.yml
  .github/workflows/e2e-full.yml
  .github/workflows/e2e.yml
  .github/workflows/linting.yml
  .github/workflows/multiarch.yml
  .github/workflows/periodic.yml
  .github/workflows/release.yml
  .github/workflows/release_subctl_on_push.yml
  .github/workflows/report.yml
  .github/workflows/system.yml
  .github/workflows/unit.yml
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test

#234 Add execute.IfServiceDiscoveryInstalled function
  cmd/subctl/execute/execute.go
  internal/constants/constants.go
  internal/gather/gather.go
  pkg/cluster/info.go
Labels: ready-to-test

#235 Collect the output of ovn-sbctl show in gather
  internal/gather/cni.go
Labels: ready-to-test, backport

#237 Check GHA updates weekly
  .github/dependabot.yml
Labels: ready-to-test

#239 Bump submariner-operator version to latest
  go.mod
  go.sum
Labels: ready-to-test

#183 submariner-diagnose: ignore diagnose pod on deployment test
  internal/constants/constants.go
  internal/pods/schedule.go
  pkg/diagnose/deployments.go
Labels: ready-to-test
