Repository submariner-io/subctl, pull requests merged in 2022-06, with the labels that each got.

#79 Clarify the diagnose firewall vxlan test output
  cmd/subctl/diagnose.go
  pkg/diagnose/firewall_vxlan.go
Labels: ready-to-test

#84 Bump submariner version
  go.mod
  go.sum
Labels: ready-to-test

#82 Use constants instead of hardcoding the ports
  cmd/subctl/cloud.go
  go.mod
  go.sum
  pkg/diagnose/cni.go
  pkg/diagnose/firewall.go
Labels: ready-to-test

#88 Use Submariner CRD image registry info for obtaining nettest image
  Makefile
  cmd/subctl/diagnose.go
  internal/pods/schedule.go
  pkg/cluster/info.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_metrics.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/kubeproxy.go
  pkg/image/repository_info.go
Labels: ready-to-test

#87 Remove unused cli Status functions
  internal/cli/status.go
Labels: ready-to-test

#95 Gather OVN LB groups
  internal/gather/cni.go
Labels: ready-to-test

#103 Rebuild subctl for any .go file change
  Makefile
Labels: ready-to-test

#104 Set client pod of firewall inter-cluster to run in hostnet
  pkg/diagnose/firewall.go
Labels: ready-to-test

#94 Setup shipyard TestContext.NettestImageURL var
  cmd/subctl/benchmark.go
  cmd/subctl/root.go
  cmd/subctl/verify.go
  go.mod
  go.sum
  internal/pods/schedule.go
  pkg/image/repository_info.go
Labels: ready-to-test

#96 Don't uninstall local broker if in use
  pkg/uninstall/all.go
Labels: ready-to-test

#100 Handle uninstall on broker-only cluster
  pkg/uninstall/all.go
Labels: ready-to-test

#101 Cloud prepare support for OVN Clusters
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/prepare.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test

#78 diagnose firewall inter-cluster: add support for LB mode
  pkg/diagnose/firewall.go
Labels: ready-to-test

#66 Build subctl images for x86-64 and ARM64
  .github/workflows/multiarch.yml
  Makefile
  package/Dockerfile.subctl
Labels: ready-to-test, release-note-needed

#126 Change default namespace for diagnose
  cmd/subctl/diagnose.go
  internal/pods/schedule.go
  pkg/diagnose/firewall.go
Labels: ready-to-test

#132 Automated backport of #126: Change default namespace for diagnose
  cmd/subctl/diagnose.go
  internal/pods/schedule.go
  pkg/diagnose/firewall.go
Labels: ready-to-test, automated-backport

#127 Warn users about ns label warnings
  internal/pods/schedule.go
Labels: ready-to-test, backport

#121 show brokers command to show broker spec
  internal/show/brokers.go
Labels: ready-to-test, backport

#133 Automated backport of #127: Add warning about missing labels
  internal/pods/schedule.go
Labels: ready-to-test, automated-backport

#135 Automated backport of #121: show brokers command to show broker spec
  internal/show/brokers.go
Labels: ready-to-test, automated-backport

#138 Update lighthouse to pull latest e2e
  go.mod
  go.sum
Labels: ready-to-test

#142 Remove extra `using` handling
  Makefile
Labels: ready-to-test
