Repository submariner-io/subctl, pull requests merged in 2022-10, with the labels that each got.

#294 Automated backport of #270: Use the default kind CNI
  .shipyard.e2e.ovn.yml
  .shipyard.e2e.yml
Labels: automated-backport

#298 Bump submariner-operator version
  go.mod
  go.sum
Labels: ready-to-test

#295 Add Sonar unit test coverage reporting
  .github/workflows/report.yml
  sonar-project.properties
Labels: ready-to-test, automation

#299 Support air-gapped flag as part of join
  cmd/subctl/join.go
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/join/options.go
  release-notes/20221014-air-gapped.md
Labels: ready-to-test, release-note-needed

#305 Defer cleanupFramework after initFramework
  internal/benchmark/latency.go
  internal/benchmark/throughput.go
Labels: ready-to-test

#296 Verify ServiceExport Synced status condition
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test

#308 Remove space between // and nolint
  cmd/subctl/aws.go
  cmd/subctl/azure.go
  cmd/subctl/deploybroker.go
  cmd/subctl/export.go
  cmd/subctl/gcp.go
  cmd/subctl/generic_cloud.go
  cmd/subctl/join.go
  cmd/subctl/rhos.go
  cmd/subctl/unexport.go
  cmd/subctl/uninstall.go
  cmd/subctl/verify.go
  internal/cli/logger.go
  internal/cli/spinner.go
  internal/gather/cni.go
  internal/gather/gather.go
  internal/gather/logs.go
  internal/gather/resource.go
  internal/gather/summary.go
  internal/nodes/nodes.go
  internal/pods/exec.go
  internal/pods/schedule.go
  internal/rbac/rbac.go
  internal/restconfig/restconfig.go
  pkg/broker/ensure.go
  pkg/broker/file.go
  pkg/broker/ipsec_psk.go
  pkg/cloud/aws/aws.go
  pkg/cloud/azure/azure.go
  pkg/cloud/cleanup/aws.go
  pkg/cloud/cleanup/azure.go
  pkg/cloud/cleanup/gcp.go
  pkg/cloud/cleanup/generic.go
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/gcp/gcp.go
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/generic.go
  pkg/cloud/prepare/rhos.go
  pkg/cloud/rhos/rhos.go
  pkg/cluster/info.go
  pkg/clusterrole/ensure.go
  pkg/clusterrolebinding/ensure.go
  pkg/deploy/broker.go
  pkg/deployment/await.go
  pkg/deployment/ensure.go
  pkg/lighthouse/ensure.go
  pkg/operator/ensure.go
  pkg/resource/create_or_update.go
  pkg/role/ensure.go
  pkg/rolebinding/ensure.go
  pkg/secret/ensure.go
  pkg/serviceaccount/ensure.go
  pkg/submariner/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test

#306 Wrap two-context diagnose commands
  cmd/subctl/diagnose.go
  internal/restconfig/restconfig.go
  scripts/test/system.sh
Labels: ready-to-test

#310 Add issues:write permission to broken links GHA
  .github/workflows/periodic.yml
Labels: ready-to-test, automation

#316 Use `nettest` image/component names from operator
  go.mod
  go.sum
  pkg/image/repository_info.go
  pkg/join/join.go
Labels: ready-to-test

#315 Wrap subctl benchmark
  cmd/subctl/benchmark.go
  cmd/subctl/diagnose.go
  cmd/subctl/verify.go
  internal/benchmark/latency.go
  internal/benchmark/throughput.go
  internal/restconfig/restconfig.go
  scripts/test/system.sh
Labels: ready-to-test, release-note-needed

#328 Update the kubeconfig release notes
  release-notes/20220919-kubeconfig.md
Labels: ready-to-test

#326 Use the canonical namespace in diagnose
  cmd/subctl/diagnose.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_natdiscovery.go
  pkg/diagnose/firewall_tunnel.go
  pkg/diagnose/firewall_vxlan.go
Labels: ready-to-test

#338 Update Shipyard to v0.14.0-rc1
  go.mod
  go.sum
Labels: ready-to-test

#332 Allow --contexts on subctl show
  cmd/subctl/show.go
  scripts/test/system.sh
Labels: ready-to-test, backport

#342 Automated backport of #332: Allow --contexts on subctl show
  cmd/subctl/show.go
  scripts/test/system.sh
Labels: ready-to-test, automated-backport

#344 Avoid errors caused by sponge's SIGPIPE
  scripts/test/system.sh
Labels: ready-to-test, backport

#343 Automated backport of #326: Use the canonical namespace in diagnose
  cmd/subctl/diagnose.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_natdiscovery.go
  pkg/diagnose/firewall_tunnel.go
  pkg/diagnose/firewall_vxlan.go
Labels: ready-to-test, automated-backport
