Repository submariner-io/subctl, pull requests merged in 2022-09, with the labels that each got.

#249 Add contents:write perms to subctl release GHA
  .github/workflows/release_subctl_on_push.yml
Labels: ready-to-test, automation

#248 Don't wait for the timeout on successful firewall tests
  pkg/diagnose/firewall.go
Labels: ready-to-test

#250 Update submariner-operator version
  go.mod
  go.sum
Labels: ready-to-test

#251 Temporarily stop checking override key
  internal/image/image.go
Labels: ready-to-test

#252 Restore override component validation
  internal/image/image.go
Labels: ready-to-test

#229 subctl diagnose: Add validation for service-discovery
  cmd/subctl/diagnose.go
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test, release-note-needed

#260 Fix shellcheck errors and add to linting GHA
  .github/workflows/linting.yml
  scripts/test/lib_subctl_gather_test.sh
  scripts/test/system.sh
Labels: ready-to-test, maintenance

#259 Don't specify images to preload
  Makefile
Labels: ready-to-test, maintenance

#264 Check if metrics-proxy daemonset is deployed
  pkg/diagnose/deployments.go
Labels: ready-to-test

#265 Consolidate Namespace constants
  cmd/subctl/benchmark.go
  cmd/subctl/uninstall.go
  cmd/subctl/verify.go
  internal/constants/constants.go
  internal/gather/gather.go
  internal/gather/types.go
  pkg/cluster/info.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
Labels: ready-to-test

#268 Add release note for service discovery diagnose
  release-notes/20220915-service-discovery.md
Labels: ready-to-test, release-note-handled

#270 Use the default kind CNI
  .shipyard.e2e.yml
  .shipyard.system.yml
Labels: ready-to-test

#220 Consolidate repo handling logic
  cmd/subctl/root.go
  internal/image/image.go
  internal/pods/schedule.go
  pkg/cluster/info.go
  pkg/deploy/broker.go
  pkg/deploy/operator.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/image/repository_info.go
  pkg/join/join.go
Labels: ready-to-test

#277 Allow the broker to watch secrets
  pkg/broker/rbac.go
Labels: ready-to-test

#261 Export service for system tests
  .github/workflows/system.yml
  scripts/test/system.sh
Labels: ready-to-test

#279 Automated backport of #277: Allow the broker to watch secrets
  pkg/broker/rbac.go
Labels: ready-to-test, automated-backport

#282 Allow kindnet in subctl diagnose
  go.mod
  go.sum
  pkg/diagnose/cni.go
Labels: ready-to-test

#258 Set privileged scc using clusterrole and clusterrolebinding
  go.mod
  go.sum
  pkg/lighthouse/ensure.go
  pkg/lighthouse/scc/ensure.go
  pkg/operator/ensure.go
  pkg/operator/ocp/ensure.go
  pkg/operator/scc/ensure.go
  pkg/scc/update.go
  pkg/submariner/ensure.go
  pkg/submariner/scc/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test, release-note-needed

#284 Fix Lighthouse CoreDNS ocp ClusterRoleBinding
  pkg/lighthouse/ensure.go
Labels: ready-to-test
