Repository submariner-io/subctl, pull requests merged in 2022-07, with the labels that each got.

#150 Fix intermittent failure with diagnose metrics cmd
  pkg/diagnose/firewall_metrics.go
Labels: ready-to-test

#151 [Backport] Fix intermittent failure with diagnose metrics cmd
  pkg/diagnose/firewall_metrics.go
Labels: ready-to-test

#152 Remove K8s E2E param, use default
  .github/workflows/e2e-full.yml
Labels: ready-to-test

#153 Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: ready-to-test, backport

#165 Automated backport of #107: Allow broker certificate checks to be disabled
  cmd/subctl/join.go
  pkg/broker/info.go
  pkg/deploy/servicediscovery.go
  pkg/deploy/submariner.go
  pkg/join/join.go
  pkg/join/options.go
Labels: ready-to-test, automated-backport

#174 Fix KIND deployments using ovn
  Makefile
Labels: ready-to-test

#173 Display proper output message on `subctl show brokers`
  internal/show/brokers.go
Labels: ready-to-test, backport

#180 Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, backport, maintenance

#177 Automated backport of #153: Bump x/text to address CVE-2021-38561
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#181 Automated backport of #180: Run the upgrade job on devel only
  .github/workflows/upgrade-e2e.yml
Labels: ready-to-test, automated-backport

#162 Gather: collect table 100 routes when vxlan used
  internal/gather/cni.go
Labels: ready-to-test

#179 Automated backport of #173: Display proper output message on `subctl show brokers`
  internal/show/brokers.go
Labels: ready-to-test, automated-backport

#172 Allow passing DEFAULT_REPO while building subctl
  Makefile
Labels: ready-to-test, backport

#184 Automated backport of #172: Allow passing DEFAULT_REPO while building subctl
  Makefile
Labels: ready-to-test, automated-backport

#185 Adjust to cloud prepare Azure API migration
  go.mod
  go.sum
  internal/restconfig/restconfig.go
  pkg/broker/ensure.go
  pkg/cloud/azure/azure.go
Labels: ready-to-test
