Repository submariner-io/subctl, pull requests merged in 2022-12, with the labels that each got.

#411 Add dependabot GHA updates for release-0.13
  .github/dependabot.yml
Labels: ready-to-test, automation

#415 Use submariner-operator ns in diagnose firewall cmd
  cmd/subctl/diagnose.go
Labels: ready-to-test, backport

#416 [Backport] Use submariner-operator ns in diagnose firewall cmd
  cmd/subctl/diagnose.go
Labels: ready-to-test, automated-backport

#417 Move cloudPorts into cloudOptions
  cmd/subctl/aws.go
  cmd/subctl/azure.go
  cmd/subctl/cloud.go
  cmd/subctl/gcp.go
  cmd/subctl/rhos.go
  go.mod
Labels: ready-to-test

#423 Fix ipvs interface missing message
  pkg/diagnose/kubeproxy.go
Labels: ready-to-test, backport

#424 Automated backport of #423: Fix ipvs interface missing message
  pkg/diagnose/kubeproxy.go
Labels: ready-to-test, automated-backport

#406 Configure dependabot for GHAs on 0.12 and 0.13
  .github/dependabot.yml
Labels: ready-to-test

#428 Bump to Go 1.19
  go.mod
  go.sum
Labels: ready-to-test

#432 Improve error reporting for failed network pods
  internal/pods/schedule.go
Labels: ready-to-test

#433 Give more permission to the diagnose pods
  internal/pods/schedule.go
Labels: ready-to-test, backport

#435 [Backport] Give more permission for the diagnode pods
  internal/pods/schedule.go
Labels: ready-to-test, automated-backport

#434 Simplify getActiveGatewayNodeName
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_vxlan.go
Labels: ready-to-test

#429 Improve diagnose firewall error output
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_vxlan.go
Labels: ready-to-test

#425 Use coreos/go-semver instead of mcuadros/go-version
  .golangci.yml
  go.mod
  go.sum
  pkg/diagnose/cni.go
Labels: dependencies, ready-to-test, maintenance

#445 Bump to Kubernetes 0.26 dependencies
  go.mod
  go.sum
  internal/gather/cni.go
  internal/pods/exec.go
  pkg/diagnose/cni.go
Labels: dependencies, ready-to-test, maintenance

#446 Stop pretending to support Kubernetes 1.17
  pkg/version/version.go
Labels: ready-to-test

#460 Automated backport of #423: Fix ipvs interface missing message
  pkg/diagnose/kubeproxy.go
Labels: ready-to-test, automated-backport

#459 Automated backport of #433: Give more permission for the diagnode pods
  internal/pods/schedule.go
Labels: ready-to-test, automated-backport

#469 Gather iptables logs for Calico and kindnet CNIs
  internal/gather/cni.go
Labels: ready-to-test, backport
