Repository submariner-io/subctl, pull requests merged in 2023-02, with the labels that each got.

#540 Improve messages when components aren't installed
  cmd/subctl/diagnose.go
  cmd/subctl/show.go
  internal/constants/constants.go
  internal/restconfig/restconfig.go
  internal/show/all.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
Labels: ready-to-test

#543 Remove redundant check for Calico CNI in subctl diagnose
  pkg/diagnose/cni.go
Labels: ready-to-test

#545 Delete failed diagnose pods
  internal/pods/schedule.go
Labels: ready-to-test

#544 Obtain label selector for gathering operator logs
  internal/gather/operator.go
  pkg/operator/deployment/ensure.go
Labels: ready-to-test, backport

#542 Force delete objects on uninstall if operator pod not running
  go.mod
  go.sum
  pkg/uninstall/all.go
Labels: ready-to-test

#552 Automated backport of #394: Look up service EndpointSlice by labels
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test, automated-backport

#548 Bump submariner-operator version
  go.mod
  go.sum
Labels: ready-to-test

#550 Diagnose validate Calico IPPool configuration
  pkg/diagnose/cni.go
Labels: ready-to-test

#551 Add support for packet size in subctl verify
  cmd/subctl/verify.go
  go.mod
  go.sum
Labels: ready-to-test

#541 Update cloud-prepare API
  go.mod
  go.sum
  pkg/cloud/cleanup/aws.go
  pkg/cloud/cleanup/azure.go
  pkg/cloud/cleanup/gcp.go
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/prepare.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test

#575 Deprecate `dedicated-gateway` for 0.15
  cmd/subctl/azure.go
  cmd/subctl/gcp.go
  cmd/subctl/rhos.go
Labels: ready-to-test
