Repository submariner-io/subctl, pull requests merged in 2023-10, with the labels that each got.

#963 Automated backport of #901: Show the architecture for each running component
  internal/show/versions.go
Labels: ready-to-test, automated-backport

#965 Bump submariner-operator version to get GN RBAC changes
  go.mod
  go.sum
Labels: ready-to-test

#970 Edit arguments given to run new upgraded subctl
  .github/workflows/upgrade-subctl.yml
  cmd/subctl/upgrade.go
Labels: ready-to-test, backport

#966 Use generic resource handling
  go.mod
  go.sum
  pkg/brokercr/ensure.go
  pkg/namespace/ensure.go
  pkg/resource/create_or_update.go
  pkg/secret/ensure.go
  pkg/serviceaccount/ensure.go
  pkg/servicediscoverycr/ensure.go
  pkg/submarinercr/ensure.go
  pkg/uninstall/all.go
Labels: ready-to-test

#972 Automated backport of #970: Edit arguments given to run new upgraded subctl
  .github/workflows/upgrade-subctl.yml
  cmd/subctl/upgrade.go
Labels: ready-to-test, automated-backport

#982 Remove cloud prepare dedicated-gateway flags
  cmd/subctl/azure.go
  cmd/subctl/gcp.go
  cmd/subctl/rhos.go
  pkg/cloud/azure/azure.go
  pkg/cloud/gcp/gcp.go
  pkg/cloud/rhos/rhos.go
Labels: ready-to-test, release-note-needed

#981 Reduce string constant duplication
  cmd/subctl/aws.go
  cmd/subctl/azure.go
Labels: ready-to-test

#983 Remove generic cloud prepare
  cmd/subctl/generic_cloud.go
  pkg/cloud/cleanup/generic.go
  pkg/cloud/generic/generic.go
  pkg/cloud/prepare/generic.go
Labels: ready-to-test, release-note-needed, release-note-handled

#985 Bump google.golang.org/grpc to v1.57.1
  go.mod
  go.sum
Labels: ready-to-test

#984 Remove release-notes files
  release-notes/20220803-subctl-directory.md
  release-notes/20220818-show-versions.md
  release-notes/20220915-service-discovery.md
  release-notes/20220919-kubeconfig.md
  release-notes/20221014-air-gapped.md
  release-notes/20221103-ovn-sbctl.md
  release-notes/20221103-privileged-scc.md
  release-notes/20230106-deprecations.md
  release-notes/20230111-gather-iptables.md
  release-notes/20230330-recover-broker-info.md
  release-notes/20230426-calico-ippools.md
  release-notes/20230426-gather-ipset.md
Labels: ready-to-test

#986 Automated backport of #979: Add LICENSE to tars
  Makefile
Labels: ready-to-test, automated-backport
