Repository submariner-io/subctl, pull requests merged in 2023-09, with the labels that each got.

#889 When upgrading, deploy with the downloaded subctl
  Makefile
Labels: ready-to-test

#903 Update versions for OVN IC fixes
  go.mod
  go.sum
Labels: ready-to-test

#888 Gather OVN IC resources
  internal/gather/cni.go
  internal/gather/connectivity.go
Labels: ready-to-test

#909 Automated backport of #886: Alert for blocked ESP protocol as part of diagnose
  pkg/diagnose/firewall.go
Labels: ready-to-test, release-note-needed, automated-backport

#897 Update Kubernetes version checks
  pkg/diagnose/k8s_version.go
  pkg/join/join.go
  pkg/version/version.go
Labels: ready-to-test

#911 Add check for OVN pods in IC deployments
  internal/gather/cni.go
  internal/gather/connectivity.go
Labels: ready-to-test

#913 Use endpoints from Broker while validating overlapping CIDRs
  pkg/diagnose/deployments.go
Labels: ready-to-test, backport

#901 Show the architecture for each running component
  internal/show/versions.go
Labels: ready-to-test

#917 upgrade: Trim prefix from current version
  cmd/subctl/upgrade.go
Labels: ready-to-test, backport

#916 Automated backport of #913: Use endpoints from Broker while validating overlapping CIDRs
  pkg/diagnose/deployments.go
Labels: ready-to-test, automated-backport

#915 Automated backport of #911: Add check for OVN pods in IC deployments
  internal/gather/cni.go
  internal/gather/connectivity.go
Labels: ready-to-test, automated-backport

#919 Automated backport of #917: upgrade: Trim prefix from current version
  cmd/subctl/upgrade.go
Labels: ready-to-test, automated-backport

#922 Remove redundant diagnose messages
  pkg/diagnose/connections.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/globalnet.go
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test, backport

#925 Ensure Data field is always set in EnsureTokenSecret
  pkg/serviceaccount/ensure.go
Labels: ready-to-test

#923 upgrade: handle release branch versions
  cmd/subctl/upgrade.go
Labels: ready-to-test, backport

#926 Automated backport of #922: Remove redundant diagnose messages
  pkg/diagnose/connections.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/globalnet.go
  pkg/diagnose/servicediscovery.go
Labels: automated-backport

#929 Automated backport of #928: Fix subctl uninstall failure if Broker CRD isn't present
  pkg/uninstall/all.go
Labels: ready-to-test, automated-backport

#927 Automated backport of #925: Ensure Data field is always set in EnsureTokenSecret
  pkg/serviceaccount/ensure.go
Labels: ready-to-test, automated-backport

#930 Automated backport of #923: upgrade: handle release branch versions
  cmd/subctl/upgrade.go
Labels: ready-to-test, automated-backport

#931 Configure dependabot for the release-0.16 branch
  .github/dependabot.yml
Labels: ready-to-test, automated

#950 Automated backport of #913: Use endpoints from Broker while validating overlapping CIDRs
  pkg/diagnose/deployments.go
Labels: ready-to-test, automated-backport
