Repository submariner-io/subctl, pull requests merged in 2023-03, with the labels that each got.

#570 Failed to diagnose calico when natOutgoing is not found
  pkg/diagnose/cni.go
Labels: ready-to-test

#568 Add compliance tests to "subctl verify"
  cmd/subctl/verify.go
Labels: ready-to-test

#589 Make getSpecBool generic, simplify its return
  pkg/diagnose/cni.go
Labels: ready-to-test

#587 Use k8s.io generic sets instead of Admiral stringset
  cmd/subctl/deploybroker.go
  cmd/subctl/gather.go
  internal/gather/gather.go
  pkg/broker/file.go
  pkg/broker/info.go
  pkg/deploy/broker.go
Labels: ready-to-test, technical-debt

#596 Fix image-overrides for diagnose kube-proxy-mode
  pkg/diagnose/kubeproxy.go
Labels: ready-to-test, backport

#595 Drop the Broker Submariner spec field
  pkg/deploy/submariner.go
Labels: ready-to-test

#599 Automated backport of #596: Fix image-overrides for diagnose kube-proxy-mode
  pkg/diagnose/kubeproxy.go
Labels: ready-to-test, automated-backport

#600 Allow overriding the metrics proxy component
  pkg/cluster/info.go
Labels: ready-to-test, backport

#603 [Backport-0.14] Include image-override as a firewall subcmd
  cmd/subctl/diagnose.go
Labels: ready-to-test, automated-backport

#611 Automated backport of #600: Allow overriding the metrics proxy component
  pkg/cluster/info.go
Labels: ready-to-test, automated-backport

#612 Bump cloud-prepare to latest, for stringset removal
  go.mod
  go.sum
Labels: ready-to-test

#467 Recover lost broker-info.subm
  cmd/subctl/recover_broker_info.go
  pkg/broker/recover_broker_info.go
  pkg/cluster/info.go
  scripts/test/system.sh
Labels: ready-to-test

#588 Refactor RecoverData to rely on WriteInfoToFile
  cmd/subctl/deploybroker.go
  pkg/broker/file.go
  pkg/broker/ipsec_psk.go
  pkg/broker/recover_broker_info.go
Labels: ready-to-test

#618 Bump submariner-operator version
  go.mod
  go.sum
Labels: ready-to-test

#627 Update subctl diagnose service-discovery
  go.mod
  go.sum
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test

#629 Bump tim-actions GHAs for node updates
  .github/workflows/linting.yml
Labels: dependencies, ready-to-test

#634 Bump submariner-operator to get status RBAC fixes
  go.mod
  go.sum
Labels: ready-to-test
