Repository submariner-io/subctl, pull requests merged in 2023-01, with the labels that each got.

#471 [Backport]Gather iptables logs for Calico and kindnet CNIs (#469)
  internal/gather/cni.go
Labels: ready-to-test, automated-backport

#472 Delete `term_test.go`
  internal/env/term_test.go
Labels: ready-to-test

#465 Ability to specify namespace for prefix context
  internal/restconfig/restconfig.go
Labels: ready-to-test

#478 Suppress pod security warnings
  cmd/subctl/root.go
Labels: ready-to-test

#474 Remove all deprecated commands and flags
  cmd/subctl/benchmark.go
  cmd/subctl/cloud.go
  cmd/subctl/deploybroker.go
  cmd/subctl/diagnose.go
  cmd/subctl/gather.go
  cmd/subctl/root.go
  cmd/subctl/uint16slice.go
  cmd/subctl/verify.go
  internal/restconfig/restconfig.go
  release-notes/20230106-deprecations.md
  scripts/test/system.sh
Labels: ready-to-test, UX, release-note-needed, release-note-handled

#492 Bump submariner-operator go mod version
  go.mod
  go.sum
Labels: ready-to-test

#494 Add release notes for PR469
  release-notes/20230111-gather-iptables.md
Labels: ready-to-test, backport

#495 Automated backport of #494: Add release notes for PR469
  release-notes/20230111-gather-iptables.md
Labels: ready-to-test, automated-backport

#470 [Backport] Gather iptables logs for Calico and kindnet CNIs (#469)
  go.mod
  go.sum
  internal/gather/cni.go
Labels: ready-to-test, automated-backport

#491 Initialize `prefixedDefaultNamespaces` before using
  internal/restconfig/restconfig.go
Labels: ready-to-test

#518 Only call cloud prepare when it's needed
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, backport

#522 Automated backport of #518: Only call cloud prepare when it's needed
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#521 Automated backport of #518: Only call cloud prepare when it's needed
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#523 Stop vendoring
  Makefile
Labels: ready-to-test, maintenance

#520 Make sure to end status on `cloud` commands
  pkg/cloud/cleanup/aws.go
  pkg/cloud/cleanup/azure.go
  pkg/cloud/cleanup/gcp.go
  pkg/cloud/cleanup/generic.go
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/generic.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test

#533 Change frequency of dependabot gh-action check to monthly
  .github/dependabot.yml
Labels: ready-to-test, maintenance

#535 [Backport 0.13] Make sure to end status on `cloud` commands
  pkg/cloud/cleanup/aws.go
  pkg/cloud/cleanup/azure.go
  pkg/cloud/cleanup/gcp.go
  pkg/cloud/cleanup/generic.go
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/generic.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#534 [Backport 0.14] Make sure to end status on `cloud` commands
  pkg/cloud/cleanup/aws.go
  pkg/cloud/cleanup/azure.go
  pkg/cloud/cleanup/gcp.go
  pkg/cloud/cleanup/generic.go
  pkg/cloud/cleanup/rhos.go
  pkg/cloud/prepare/aws.go
  pkg/cloud/prepare/azure.go
  pkg/cloud/prepare/gcp.go
  pkg/cloud/prepare/generic.go
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#526 Allow overriding images
  cmd/subctl/benchmark.go
  cmd/subctl/diagnose.go
  cmd/subctl/join.go
  cmd/subctl/root.go
  cmd/subctl/verify.go
  pkg/cluster/info.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/kubeproxy.go
  pkg/join/join.go
Labels: ready-to-test

#539 Automated backport of #526: Allow overriding images
  cmd/subctl/benchmark.go
  cmd/subctl/diagnose.go
  cmd/subctl/join.go
  cmd/subctl/root.go
  cmd/subctl/verify.go
  pkg/cluster/info.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/kubeproxy.go
  pkg/join/join.go
Labels: ready-to-test, automated-backport

#538 Ignore k8s dependencies included with apiextensions-apiserver
  .github/dependabot.yml
Labels: ready-to-test, maintenance
