Repository submariner-io/subctl, pull requests merged in 2023-05, with the labels that each got.

#718 Update Shipyard to v0.14.4
  go.mod
  go.sum
Labels: ready-to-test

#723 cross build for Darwin arm64
  Makefile
Labels: ready-to-test

#722 Automated backport of #657: Fix flag for unexport service command
  cmd/subctl/unexport.go
Labels: ready-to-test, automated-backport

#726 Subctl gather to include iptables and ovn-sbctl output
  internal/gather/cni.go
Labels: ready-to-test, backport

#728 Automated backport of #726: Subctl gather to include iptables and ovn-sbctl output
  internal/gather/cni.go
Labels: ready-to-test, automated-backport

#727 Automated backport of #726: Subctl gather to include iptables and ovn-sbctl output
  internal/gather/cni.go
Labels: ready-to-test, automated-backport

#652 Use embeded broker rbacs
  go.mod
  go.sum
  pkg/broker/ensure.go
  pkg/broker/rbac.go
Labels: ready-to-test

#734 Update the subctl description
  cmd/subctl/root.go
Labels: ready-to-test

#745 Bump sigs.k8s.io/controller-runtime from 0.14.6 to 0.15.0
  cmd/subctl/recover_broker_info.go
  go.mod
  go.sum
  internal/gather/gather.go
  internal/show/brokers.go
  pkg/broker/info.go
  pkg/cluster/info.go
  pkg/uninstall/all.go
Labels: ready-to-test
