Repository submariner-io/subctl, pull requests merged in 2023-04, with the labels that each got.

#645 Support for manual trigger of release image job
  .github/workflows/release.yml
Labels: ready-to-test

#635 Bump submariner-operator to get status RBAC fixes
  go.mod
  go.sum
Labels: ready-to-test

#630 Add release note for new recover-broker-info command
  release-notes/20230330-recover-broker-info.md
Labels: ready-to-test

#649 Print broker info subm file when not same
  pkg/broker/file.go
  scripts/test/system.sh
Labels: ready-to-test, backport

#655 Enable ginkgolinter
  .golangci.yml
Labels: ready-to-test

#657 Fix flag for unexport service command
  cmd/subctl/unexport.go
Labels: ready-to-test

#664 Automated backport of #662: Rename the system test exported service
  scripts/test/system.sh
Labels: ready-to-test, automated-backport

#665 Automated backport of #657: Fix flag for unexport service command
  cmd/subctl/unexport.go
Labels: ready-to-test, automated-backport

#667 [0.14] Bump tim-actions GHAs for node updates
  .github/workflows/linting.yml
Labels: ready-to-test

#663 [Backport] Print broker info subm file when not same
  pkg/broker/file.go
  scripts/test/system.sh
Labels: ready-to-test

#676 Automated backport of #654: Gather ipset details from all the nodes
  internal/gather/cni.go
Labels: ready-to-test, automated-backport

#682 Automated backport of #654: Gather ipset details from all the nodes
  internal/gather/cni.go
Labels: automated-backport

#679 Create internal SG before creating machineset
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test

#684 Automated backport of #679: Create internal SG before creating machineset
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#687 Automated backport of #679: Create internal SG before creating machineset
  pkg/cloud/prepare/rhos.go
Labels: automated-backport

#686 Automated backport of #679: Create internal SG before creating machineset
  pkg/cloud/prepare/rhos.go
Labels: ready-to-test, automated-backport

#694 Automated backport of #645: Support for manual trigger of release image job
  .github/workflows/release.yml
Labels: ready-to-test, automated-backport

#698 Release notes for gathering ipset details
  release-notes/20230426-gather-ipset.md
Labels: ready-to-test, backport

#699 Release notes for Calico IPPool validation
  release-notes/20230426-calico-ippools.md
Labels: ready-to-test, backport

#696 Automated backport of #645: Support for manual trigger of release image job
  .github/workflows/release.yml
Labels: ready-to-test, automated-backport

#702 Automated backport of #698: Release notes for gathering ipset details
  release-notes/20230426-gather-ipset.md
Labels: ready-to-test, automated-backport

#700 Automated backport of #698: Release notes for gathering ipset details
  release-notes/20230426-gather-ipset.md
Labels: ready-to-test, automated-backport

#703 Automated backport of #699: Release notes for Calico IPPool validation
  release-notes/20230426-calico-ippools.md
Labels: ready-to-test, automated-backport
