Repository submariner-io/subctl, pull requests merged in 2023-06, with the labels that each got.

#749 Automated backport of #735: Check service existence in SD diagnose
  pkg/diagnose/servicediscovery.go
Labels: ready-to-test, automated-backport

#763 Check for request construction errors
  internal/pods/exec.go
  pkg/diagnose/cni.go
Labels: ready-to-test

#752 Collect metrics pod info as part of gather
  internal/gather/connectivity.go
  internal/gather/gather.go
  internal/gather/operator.go
Labels: ready-to-test

#754 Create subctl.tar.gz as well
  Makefile
Labels: ready-to-test

#770 Fix error while running gather in GN setup
  internal/gather/connectivity.go
Labels: ready-to-test

#775 Use Submariner.Status.Version for 'gather' summary
  go.mod
  go.sum
  internal/gather/summary.go
Labels: ready-to-test

#782 Add air-gapped flag for Azure cloud prepare
  cmd/subctl/azure.go
  cmd/subctl/join.go
  go.mod
  go.sum
  pkg/cloud/azure/azure.go
  pkg/cloud/prepare/azure.go
Labels: ready-to-test, backport, release-note-needed

#786 Create sha256 checksums for all binaries
  Makefile
Labels: ready-to-test

#793 Automated backport of #782: Add air-gapped flag for Azure cloud prepare
  cmd/subctl/azure.go
  cmd/subctl/join.go
  go.mod
  go.sum
  pkg/cloud/azure/azure.go
  pkg/cloud/prepare/azure.go
Labels: ready-to-test, automated-backport

#790 Disable depguard
  .golangci.yml
Labels: ready-to-test

#792 Automated backport of #782: Add air-gapped flag for Azure cloud prepare
  cmd/subctl/azure.go
  cmd/subctl/join.go
  go.mod
  go.sum
  pkg/cloud/azure/azure.go
  pkg/cloud/prepare/azure.go
Labels: ready-to-test, automated-backport

#797 Add missing components to show versions
  internal/show/versions.go
Labels: ready-to-test

#810 Automated backport of #723: cross build for Darwin arm64
  Makefile
Labels: ready-to-test, automated-backport

#811 Automated backport of #723: cross build for Darwin arm64
  Makefile
Labels: ready-to-test, automated-backport

#808 Automated backport of #797: Add missing components to show versions
  internal/show/versions.go
Labels: ready-to-test, automated-backport

#805 Explicitly register the operator types
  cmd/subctl/root.go
Labels: ready-to-test

#809 Automated backport of #736: diagnose: Use case-insensitive comparison for CNI name
  pkg/diagnose/cni.go
Labels: ready-to-test, automated-backport

#814 Automated backport of #775: Use Submariner.Status.Version for 'gather' summary
  go.mod
  go.sum
  internal/gather/summary.go
Labels: ready-to-test, automated-backport

#806 Disable dependabot PRs for parent-managed dependencies
  .github/dependabot.yml
Labels: ready-to-test

#791 Switch to depguard v2 configuration
  .golangci.yml
  internal/gather/resource.go
Labels: ready-to-test
