Repository submariner-io/subctl, pull requests merged in 2023-11, with the labels that each got.

#989 Update grpc to fix GHSA-m425-mq94-257g CVE
  go.mod
  go.sum
Labels: security

#964 [Backport-0.13] Use endpoints from Broker while validating overlapping CIDRs
  pkg/diagnose/deployments.go
Labels: ready-to-test

#1003 [0.16] Bump shipyard version
  go.mod
  go.sum
Labels: ready-to-test

#1005 Correct the non_deploy flag used in upgrade command
  cmd/subctl/upgrade.go
Labels: ready-to-test, backport

#1006 Update grpc to fix CVEs
  go.mod
  go.sum
Labels: ready-to-test, security

#1008 Override the ImageMagick license detection
  .lichen.yaml
Labels: ready-to-test

#1012 Updates to fix CVEs
  go.mod
  go.sum
Labels: security

#1013 Automated backport of #1005: Correct the non_deploy flag used in upgrade command
  cmd/subctl/upgrade.go
Labels: ready-to-test, automated-backport

#1014 Switch from stale app to stale GHA
  .github/stale.yml
  .github/workflows/stale.yml
Labels: ready-to-test, automation
