Repository submariner-io/subctl, pull requests merged in 2024-04, with the labels that each got.

#1090 Backport fixes to validate_and_clean_broker_info
  scripts/test/system.sh
Labels: ready-to-test

#1088 Update protobuf to 1.33.0 for GO-2024-2611
  go.mod
  go.sum
Labels: ready-to-test, security

#1086 Enhance --image-override verification
  cmd/subctl/benchmark.go
  cmd/subctl/diagnose.go
  cmd/subctl/join.go
  cmd/subctl/root.go
  cmd/subctl/verify.go
  pkg/cluster/info.go
  pkg/diagnose/deployment_metrics.go
  pkg/diagnose/deployments.go
  pkg/diagnose/firewall.go
  pkg/diagnose/firewall_vxlan.go
  pkg/diagnose/kubeproxy.go
  scripts/test/system.sh
Labels: ready-to-test

#1097 Match Ginkgo signature for By
  go.mod
  go.sum
  internal/benchmark/throughput.go
Labels: ready-to-test

#1104 Update protobuf to 1.33.0 for GO-2024-2611
  go.mod
  go.sum
Labels: ready-to-test, security

#1105 Update protobuf to 1.33.0 for GO-2024-2611
  go.mod
  go.sum
Labels: ready-to-test, security

#1103 Add HTTP proxy args to subctl join, deploy-broker and upgrade commands
  cmd/subctl/deploybroker.go
  cmd/subctl/join.go
  cmd/subctl/root.go
  cmd/subctl/upgrade.go
  pkg/deploy/broker.go
  pkg/join/join.go
  pkg/join/options.go
  pkg/operator/deployment/ensure.go
  pkg/operator/ensure.go
Labels: ready-to-test, release-note-needed

#1099 Make subctl verify output more useful
  cmd/subctl/verify.go
  go.mod
  go.sum
  scripts/test/system.sh
Labels: ready-to-test, release-note-needed
