Repository submariner-io/subctl, pull requests merged in 2024-03, with the labels that each got.

#1077 Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, backport

#1081 Automated backport of #1077: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1082 Automated backport of #1077: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1079 Automated backport of #1077: Only fail builds for high+ vulns
  .github/workflows/linting.yml
Labels: ready-to-test, automated-backport

#1084 Verify no args are passed to subctl gather
  cmd/subctl/gather.go
  scripts/test/system.sh
Labels: ready-to-test

#1089 Update protobuf to 1.33.0 for GO-2024-2611
  go.mod
  go.sum
Labels: ready-to-test, security

#1087 Update protobuf to 1.33.0 for GO-2024-2611
  go.mod
  go.sum
Labels: ready-to-test, security
