Repository submariner-io/subctl, pull requests merged in 2024-05, with the labels that each got.

#1120 Automated backport of #1114: Bump submariner-operator for RBAC updates
  go.mod
  go.sum
Labels: ready-to-test, automated-backport

#1121 Bump submariner-operator for RBAC fixes
  go.mod
  go.sum
Labels: ready-to-test

#1118 Automated backport of #1114: Bump submariner-operator for RBAC updates
  go.mod
  go.sum
  pkg/submariner/serviceaccount/ensure.go
Labels: ready-to-test, automated-backport

#1119 Automated backport of #1114: Bump submariner-operator for RBAC updates
  go.mod
  go.sum
  pkg/submariner/serviceaccount/ensure.go
Labels: ready-to-test, automated-backport

#1125 Bump submariner-operator to get RBAC changes
  cmd/subctl/join.go
  go.mod
  go.sum
  internal/show/network.go
  pkg/broker/ensure.go
  pkg/cloud/prepare/prepare.go
  pkg/deploy/broker.go
  pkg/join/join.go
Labels: ready-to-test

#1123 Use tables to drive CRD setup
  pkg/gateway/crds.go
  pkg/operator/crds/ensure.go
Labels: ready-to-test

#1127 Adjust to golangci-lint 1.58.0
  .golangci.yml
Labels: ready-to-test

#1124 Adjust to IsMissingNamespaceErr API change
  go.mod
  go.sum
  pkg/submariner/serviceaccount/ensure.go
Labels: ready-to-test

#1128 Set the operator up with enforced secrets
  go.mod
  go.sum
  pkg/join/join.go
  pkg/serviceaccount/ensure.go
Labels: ready-to-test, backport

#1131 Diagnose deployment - verify that only single GW pod labeled as active
  pkg/diagnose/deployments.go
Labels: ready-to-test

#1132 Adjust to submariner-operator RA OVN RBAC changes
  go.mod
  go.sum
  pkg/submariner/serviceaccount/ensure.go
Labels: ready-to-test

#1133 Bump submariner-operator for RA secrets RBAC updates
  go.mod
  go.sum
  pkg/submariner/serviceaccount/ensure.go
Labels: ready-to-test

#1134 Automated backport of #1133: Bump submariner-operator for RA secrets RBAC updates
  go.mod
  go.sum
  pkg/submariner/serviceaccount/ensure.go
Labels: ready-to-test, automated-backport
