Repository submariner-io/subctl, pull requests merged in 2025-05, with the labels that each got.

#1387 Bump x/net for various CVEs
  go.mod
  go.sum
Labels: ready-to-test, security

#1388 Bump x/net for various CVEs
  go.mod
  go.sum
Labels: ready-to-test, security

#1389 Bump x/net for various CVEs
  go.mod
  go.sum
Labels: ready-to-test, security

#1381 Bump azidentity for CVE-2024-35255
  go.mod
  go.sum
Labels: ready-to-test, security

#1382 Bump azidentity for CVE-2024-35255
  go.mod
  go.sum
Labels: ready-to-test, security

#1390 Identify the RouteAgent instance when logging connections for diagnose
  pkg/diagnose/connections.go
Labels: ready-to-test

#1393 Add Konflux/Renovate config to only update Tekton
  .github/renovate.json
Labels: ready-to-test, automation
